name: Build and Release Tweak

permissions:
  contents: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cleanup:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Cleaning up existing releases and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete release --yes || true
          git push origin :refs/tags/release || true

  build:
    needs: cleanup
    runs-on: macos-14
    strategy:
      matrix:
        scheme: [rootful, rootless, roothide]
        include:
          - scheme: rootful
            scheme_arg: ""
          - scheme: rootless
            scheme_arg: "THEOS_PACKAGE_SCHEME=rootless"
          - scheme: roothide
            scheme_arg: "THEOS_PACKAGE_SCHEME=roothide"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Theos
        uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: "waruhachi/theos"
          theos-branch: "main"
          sdks-src: "waruhachi/sdks"
          sdks-branch: "main"

      - name: Build Package
        shell: bash
        run: |
          make clean package FINALPACKAGE=1 ${{ matrix.scheme_arg }}

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.scheme }}-package
          path: packages/*.deb

  cyan:
    needs: build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          path: packages
          merge-multiple: true

      - name: Generate cyan package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download release --repo TheWinner02/SideloadFix --pattern 'SideloadFix.dylib' --dir .
          gh release download release --repo TheWinner02/NSEFix --pattern 'NSEFix.dylib' --dir .
          
          TWEAK=$(ls com.choco.tg_*_iphoneos-arm.deb | head -n1)
          TGEXTRA_VERSION=$(echo "$TWEAK" | sed -E 's/com\.choco\.tg_([0-9\.]+)_.+\.deb/\1/')

          pip install --force-reinstall https://github.com/iOSDecrypted/cyanide/archive/main.zip
          cgen -o "./packages/com.choco.tg_$TGEXTRA_VERSION.cyan" -dqg -f ./SideloadFix.dylib ./NSEFix.dylib "$TWEAK" 

      - name: Upload cyan
        uses: actions/upload-artifact@v4
        with:
          name: cyan-package
          path: packages/*.cyan

  release:
    needs: cyan
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          path: packages
          merge-multiple: true

      - name: Generate Checksums
        id: metadata
        shell: bash
        run: |
          for pkg in packages/*_iphoneos-arm.deb; do
            if [ -f "$pkg" ]; then
              echo "### Rootful (iphoneos-arm)" >> release_body.md
              echo "* MD5: $(md5 -q $pkg)" >> release_body.md
              echo "* SHA1: $(shasum -a 1 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "* SHA256: $(shasum -a 256 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "" >> release_body.md
              break
            fi
          done

          for pkg in packages/*_iphoneos-arm64.deb; do
            if [ -f "$pkg" ]; then
              echo "### Rootless (iphoneos-arm64)" >> release_body.md
              echo "* MD5: $(md5 -q $pkg)" >> release_body.md
              echo "* SHA1: $(shasum -a 1 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "* SHA256: $(shasum -a 256 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "" >> release_body.md
              break
            fi
          done

          for pkg in packages/*_iphoneos-arm64e.deb; do
            if [ -f "$pkg" ]; then
              echo "### RootHide (iphoneos-arm64e)" >> release_body.md
              echo "* MD5: $(md5 -q $pkg)" >> release_body.md
              echo "* SHA1: $(shasum -a 1 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "* SHA256: $(shasum -a 256 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "" >> release_body.md
              break
            fi
          done

          for pkg in packages/*.cyan; do
            if [ -f "$pkg" ]; then
              echo "### Cyan Package" >> release_body.md
              echo "* MD5: $(md5 -q $pkg)" >> release_body.md
              echo "* SHA1: $(shasum -a 1 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "* SHA256: $(shasum -a 256 $pkg | awk '{ print $1 }')" >> release_body.md
              echo "" >> release_body.md
              break
            fi
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release
          name: ${{ github.event.repository.name }}
          body_path: release_body.md
          files: |
            packages/*.deb
            packages/*.cyan
          draft: false
          prerelease: false
          make_latest: true

      - name: Delete build artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            rootful-package
            rootless-package
            roothide-package
            cyan-package
          failOnError: false
